### ISSUE TITLE
非Root方式获取com.tencent.mobileqq后无法找到目标文件

### ISSUE THREAD

**Issue by HuilanYM** [Young-Lord/QQ-History-Backup#10]
FileNotFoundError('无法找到目标文件！\n路径：J:/UNKNOW/UNKNOW/backup_qq/Android/data/com.tencent.mobileqq\n当前匹配列表：[None, None, None]')Traceback (most recent call last):
  File "e:\SOFTWAVE\QQ-History-Backup-master\QQ-History-Backup-master\QQ_History.py", line 582, in main
    q = QQoutput(base_path, str(qq_self), emoji, with_img, combine_img)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\SOFTWAVE\QQ-History-Backup-master\QQ-History-Backup-master\QQ_History.py", line 66, in __init__
    self.init_paths()
  File "e:\SOFTWAVE\QQ-History-Backup-master\QQ-History-Backup-master\QQ_History.py", line 409, in init_paths
    raise FileNotFoundError(
FileNotFoundError: 无法找到目标文件！
路径：J:/UNKNOW/UNKNOW/backup_qq/Android/data/com.tencent.mobileqq
当前匹配列表：[None, None, None]
[PRINT]: Traceback (most recent call last):
  File "e:\SOFTWAVE\QQ-History-Backup-master\QQ-History-Backup-master\QQ_History.py", line 582, in main
    q = QQoutput(base_path, str(qq_self), emoji, with_img, combine_img)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\SOFTWAVE\QQ-History-Backup-master\QQ-History-Backup-master\QQ_History.py", line 66, in __init__
    self.init_paths()
  File "e:\SOFTWAVE\QQ-History-Backup-master\QQ-History-Backup-master\QQ_History.py", line 409, in init_paths
    raise FileNotFoundError(
FileNotFoundError: 无法找到目标文件！
路径：J:/UNKNOW/UNKNOW/backup_qq/Android/data/com.tencent.mobileqq
当前匹配列表：[None, None, None]

我是通过通过手机自带的备份工具备份整个 QQ，拷贝备份文件到电脑，解压找到 com.tencent.mobileqq
但通过GUI选取com.tencent.mobileqq文件夹后无法找到目标文件
作为第一次使用GITHUB的纯小白，现在能看懂的就是com.tencent.mobileqq与那三个文件相关，不知道是哪一步出错了。
是我的com.tencent.mobileqq里没有这三个文件导致无法找到目标文件又或者是别的原因？
对了，从手机上复制下来有三个文件分别是backup_qq.zip（com.tencentmobileqq的来源），QQ(com.tencent.mobileqq).bak，和descript.xml。
路径中的个人隐私部分用UNKNOW替代了

寻找到这个项目的原因是因为QQ手机的聊天记录搜索无法查询到早期聊天记录，需要手翻，通过QQ自带的备份功能备份到电脑上也有缺失的聊天记录（手机是能翻到显示出来的），想用此方法将所有本地聊天记录全部导出（另外一台IOS可能之后也要折腾把旧记录导出）。新手真是令人头疼，一个简单的环境报错了不少，花了不少时间搭。

**Comment by HuilanYM** [comment]
参考了另外一个Open的问题，发现我的com.tencentmobileqq里并没有需要的database这几个文件，让我感到很疑惑，其次是不大明白这个项目该如何应用在Windows下PC版的QQ上。

**Comment by HuilanYM** [comment]
个人从B站上找到其他恢复软件（估计是同样的底层吧，没有自己编译过代码并不了解程序运行逻辑），发现MIUI这一套逻辑是将QQ(com.tencent.mobileqq).bak通过7-ZIP解压开后修改db文件夹名为"databases"，将f文件夹名修改为"files"后
重新运行GUI.py，选取7-ZIP解压的这个新com.tencent.mobileqq成功导出了HTML并且是从安卓手机上本地保存的聊天记录，
这让我感到十分兴奋，希望能帮到其他用户，下一次将尝试带着图片导出和苹果手机导出，试着为大家排障。

**Comment by Young-Lord** [comment]
> 参考了另外一个Open的问题，发现我的com.tencentmobileqq里并没有需要的database这几个文件，让我感到很疑惑，其次是不大明白这个项目该如何应用在Windows下PC版的QQ上。

PC 的暂时不能导出，在写

**Comment by Young-Lord** [comment]
没什么问题我就先 close 了？如果想写一个详细教程的话欢迎~

**Comment by HuilanYM** [comment]
好的没有问题！

**Comment by HuilanYM** [comment]
好的没有问题！
