### ISSUE TITLE
现在还可以正常使用吗？

### ISSUE THREAD

**Issue by yingzi66-yep** [Young-Lord/QQ-History-Backup#12]
为什么我只能导出一天的聊天记录

**Comment by Young-Lord** [comment]
QQ版本？数据库文件？

**Comment by yingzi66-yep** [comment]
你好，感谢回复
QQ版本为8.9.78.610
数据库文件是指QQ号.db吗？那三个文件都找到了

**Comment by Young-Lord** [comment]
这个版本可能是 QQNT，数据已经转移到新版本的数据库里了，详见 QQBackup/qq-win-db-key#38 。验证的话可以看一下有没有`/databases/nt_db`这个目录。
目前还没有实现解析，不过 Windows 端的数据库密钥提取+解密 和 Android 端的密钥提取 都已经实现了，具体参见https://github.com/Young-Lord/qq-win-db-key

**Comment by Young-Lord** [comment]
相关 issue:
https://github.com/Hakuuyosei/QQHistoryExport/issues/5

**Comment by ygjsz** [comment]
> 你好，感谢回复 QQ版本为8.9.78.610 数据库文件是指QQ号.db吗？那三个文件都找到了

8.9.78确实已经是QQ NT了 你得按照https://github.com/Young-Lord/qq-win-db-key 的办法提取key

更新：不行 8.9.78上vmp了

**Comment by Young-Lord** [comment]
关于跨版本适配：`FF4302D1FD7B03A9FC6F04A9FA6705A9F85F06A9F65707A9F44F08A9FDC3009154D03BD5881640F9F80304AAF50303AAF60302AA`这个sig目前看起来是能用的，直接拿这个找函数（大概）就没问题

**Comment by Young-Lord** [comment]
QQNT + 长时间未回复，close
