### ISSUE TITLE
请问ios的备份可以使用吗

### ISSUE THREAD

**Issue by lsrfsy** [Young-Lord/QQ-History-Backup#2]
我备份出来的qq.db可以直接用数据库软件打开，但是和安卓目录不一样，我找不到图片和语音文件

**Comment by Young-Lord** [comment]
不好意思，不了解ios，还请询问其他人呢
（要是能把答案发上来就更好了 感谢！）

**Comment by Young-Lord** [comment]
看到你在原repo也发了评论，就移到那边讨论吧。这个issue先锁了。
https://github.com/Yiyiyimu/QQ-History-Backup/issues/42
