### ISSUE TITLE
安装环境报错

### ISSUE THREAD

**Issue by CatzTimes** [Young-Lord/QQ-History-Backup#5]
![$JQ ERWFGKF6X@XG_X{LM24](https://user-images.githubusercontent.com/62692767/213916427-52d05204-429d-41e9-9f49-a07d71250d1b.png)
![Z8U_H50`8T{3G08 8MNRCA1](https://user-images.githubusercontent.com/62692767/213916441-dcfb02cc-60c2-420b-a68a-05bd3d6ec058.png)

**Comment by Young-Lord** [comment]
你可能需要在Visual Studio Installer里安装Windows SDK
又及，pilk相关问题本来并不应在这里提问，但倒是提醒了我应该加个可执行文件版pilk支持就是了

**Comment by CatzMR** [comment]
我换了一个环境
然后他这样的报错您看看
![TMIW5N)TU7$PVT _8($GCYU](https://user-images.githubusercontent.com/62692767/213920865-0c21633e-6f65-4d11-ad5e-c746cc963bb2.png)

**Comment by Young-Lord** [comment]
> 我换了一个环境 然后他这样的报错您看看 ![TMIW5N)TU7$PVT _8($GCYU](https://user-images.githubusercontent.com/62692767/213920865-0c21633e-6f65-4d11-ad5e-c746cc963bb2.png)



能看一下你的程序框里是怎么配置的吗，这个是说找不到群号对应的群名

**Comment by CatzMR** [comment]
![SUA`GPB5)R1Z) AUO7HC(3T](https://user-images.githubusercontent.com/62692767/213922096-e10958c2-e7bd-4745-b62c-0c07ddf02fae.png)

**Comment by CatzTimes** [comment]
那个什么 我这个截图 是后来你要截图的时候重新打开重新输入的
那个是群聊 这次截图的时候忘记点群聊的 但是那个错误的时候我的确点的群聊

**Comment by Young-Lord** [comment]
果然 我还翻了半天代码在那想
还有 有个人信息的这几张图我给你删了？

**Comment by CatzTimes** [comment]
可以可以 您看过了删就行

**Comment by CatzTimes** [comment]
> 拥有

还有我解释一下 我只是发错截图了...  那个 我输入的的确是群号 那个报错就是提取那个群的聊天记录 弄不出来报错的

**Comment by CatzTimes** [comment]
![SFKQ3J6%@2YW 8 _0 7X9@T](https://user-images.githubusercontent.com/62692767/213923367-1c984881-22c6-4a25-8828-16258e1c8fec.png)
就是这样的

**Comment by Young-Lord** [comment]
欸 要不更新下我刚写的版本再试试
这个群是不在群聊列表里吗？我刚才写的是忽略群聊名字是否存在强行（尝试）提取

**Comment by CatzTimes** [comment]
是的，不在现在的群列表里

**Comment by Young-Lord** [comment]
那就把`QQ_History.py`更新一下
`GUI.py`是否更新均可

> 是的，不在现在的群列表里

**Comment by CatzTimes** [comment]
PS D:\QQ-History-Backup-master> python gui.py
  File "gui.py", line 19
    group = 1 if e4.get() == '私聊' else 2
    ^
SyntaxError: invalid syntax

我更新了GUI.py 尝试了下 直接报错这个

**Comment by Young-Lord** [comment]
> PS D:\QQ-History-Backup-master> python gui.py File "gui.py", line 19 group = 1 if e4.get() == '私聊' else 2 ^ SyntaxError: invalid syntax
> 
> 我更新了GUI.py 尝试了下 直接报错这个

好了 再更新一下`GUI.py`

**Comment by CatzTimes** [comment]
![(TU3NL8UOZKL1PIV L`${{5](https://user-images.githubusercontent.com/62692767/213923785-6a84d09b-828d-4779-82c6-4f5e4e8a4b4d.png)
目前还是报错这个

**Comment by Young-Lord** [comment]
> ![(TU3NL8UOZKL1PIV L`${{5](https://user-images.githubusercontent.com/62692767/213923785-6a84d09b-828d-4779-82c6-4f5e4e8a4b4d.png) 目前还是报错这个

先把`QQ_History.py`更新了 你这是只更新了GUI

**Comment by CatzMR** [comment]
警告：541350613无法在群聊列表内找到，请检查聊天类型是否填写正确
541350613_2没有聊天记录，跳过。
..就连图片都没有吗？

**Comment by Young-Lord** [comment]
> 警告：541350613无法在群聊列表内找到，请检查聊天类型是否填写正确 541350613_2没有聊天记录，跳过。
> 
> ..就连图片都没有吗？

往好的想，至少这个群还有一点痕迹，否则会直接报错

而且这里的“消息”指的其实是一条任何类型的消息（文本、语音、戳一戳、图片等），就算图片文件还在，数据库里没有的话你也不知道对应关系

slowtable也获取过来了吗？QQ移动端还能以任何方式看到此群的聊天记录吗？

**Comment by CatzTimes** [comment]
slowtable 这个不太了解 我使用的手机备份功能弄出来的

**Comment by Young-Lord** [comment]
> slowtable 这个不太了解 我使用的手机备份功能弄出来的

那应该就不是这个的问题了 第二个问题呢？

**Comment by CatzTimes** [comment]
我就是没有任何方式看到这个群的聊天记录 才四处找工具提取 里面有我需要提交给警察叔叔的截图

**Comment by Young-Lord** [comment]
> 我就是没有任何方式看到这个群的聊天记录 才四处找工具提取 里面有我需要提交给警察叔叔的截图

那很不幸，本地数据已经没有了，如果事件比较大的话建议报案后找tx官方要云端记录，非常抱歉帮不上忙…

**Comment by CatzTimes** [comment]
QQ还会自己删本地数据啊？

**Comment by CatzTimes** [comment]
电脑端我觉得可能有记录 但是我没找到能用的电脑端聊天记录提取软件

**Comment by Young-Lord** [comment]
对于是否会自己删我不清楚
电脑端聊天记录管理器本身就能导出txt

**Comment by CatzTimes** [comment]
但是不支持已退群的........

**Comment by Young-Lord** [comment]
> 但是不支持已退群的........

要是正常方法都看不到可能也没戏（就算可能有也[非常麻烦](https://www.52pojie.cn/thread-1370802-1-1.html)）
